// utils/cloudinary.js
// KNOWN ACCEPTED RISK: the installed cloudinary@1.41.3 has a high-severity
// CVE (GHSA-g4mf-96x5-5m2c, arbitrary argument injection via a parameter
// value containing "&"), fixed only in cloudinary@2.7.0+ — a major version.
// multer-storage-cloudinary (even its latest release, 4.0.0) has never
// added support for it; its peer dependency is still `cloudinary: ^1.21.0`,
// so installing the patched cloudinary v2 here would break the
// CloudinaryStorage integration this file exists to configure. Accepted
// rather than worked around because the vulnerable code path requires
// attacker-controlled input to reach a Cloudinary API parameter — this app
// never does that: the upload folder below is a hardcoded constant, and
// every asset's public_id is generated by Cloudinary itself, never
// supplied by a request. Re-evaluate if multer-storage-cloudinary ever
// ships v2 support, or if any Cloudinary call here starts accepting
// request-controlled parameter values.
const cloudinary = require("cloudinary").v2;
const logger = require("./logger");

const { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;

const isConfigured = Boolean(
  CLOUDINARY_CLOUD_NAME && CLOUDINARY_API_KEY && CLOUDINARY_API_SECRET,
);

// POST /upload (and every student photo replace/delete) is unusable
// without real Cloudinary credentials — failing loudly at boot means a
// missing env var is caught immediately in the terminal, not discovered
// later as a confusing 500 on the first upload attempt in production.
// Skipped under NODE_ENV=test: the test suite mocks this module rather
// than exercising real Cloudinary calls (see tests/unit/students.test.js),
// so it has no need for real credentials to exist.
if (!isConfigured && process.env.NODE_ENV !== "test") {
  logger.error(
    "Missing Cloudinary configuration: CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET must all be set.",
  );
  process.exit(1);
}

cloudinary.config({
  cloud_name: CLOUDINARY_CLOUD_NAME,
  api_key: CLOUDINARY_API_KEY,
  api_secret: CLOUDINARY_API_SECRET,
});

module.exports = cloudinary;
